config/routes.rb
Specmaker::Application.routes.draw do
  get "welcome/index"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :specsheets do 
    resources :bowls, :except => [:index]
  end

  resources :users, :only => [:index, :show, :new, :create]
  resources :sessions, :only => [:create, :new, :destroy]

  root 'specsheets#new'

end

app/models/bowl.rb
class Bowl < ActiveRecord::Base
	belongs_to :specsheet
	# validates :left_right, :front_back, :depth, :bottom_grid, :colander, :specsheet_id, presence: true, on: :update
end

app/models/specsheet.rb
class Specsheet < ActiveRecord::Base
has_many :bowls
belongs_to :user
attr_accessor :spec

# validates :installation, :corner_radius, :drain_location, :drain_size, :divider, presence: true, if: :active?
# # validates :installation, inclusion: [true, false], if :active_or_step3?
# validates :name, presence: true, if: :active_or_new?
# # validates_associated :bowls, if: :active_or_step2?

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :specsheets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
 before_filter :load_specsheet
 skip_before_action :verify_authenticity_token, only: [:update]

 def new
 	@bowl = Bowl.new
 end

 def show
 	@bowl = bowl.find(params[:id])
 end

 def create
	if params[:bowls].present? && @specsheet.bowls.count == 0
		number_of_bowls = params[:bowls].to_i
		number_of_bowls.times do 
 			@bowl = @specsheet.bowls.build
 			@bowl.save
 			@bowl.specsheet_id = @specsheet.id
 			redirect_to edit_specsheet_path(@specsheet)
 		end
 	else
 		render :new
 	end
 end

# def edit
# 	@bowl = Bowl.find(params[:bowls][0][:bowlId])
# end

	def update
		bowls = params[:bowls].map do |k,v|
			bowl = Bowl.find(v[:bowlId])
			bowl.left_right = v[:bowl][:left_right]
			bowl.front_back = v[:bowl][:front_back]
			bowl.depth = v[:bowl][:depth]
			bowl.bottom_grid = v[:bowl][:bottom_grid]
			bowl.colander = v[:bowl][:colander]
			bowl.save
		end
		respond_to do |format|
			format.json {render :json => { bowls: bowls }}
		end
	end

	def delete
		@bowl = Bowl.find(params[:id])
		@bowl.destroy
		redirect_to bowls_path
	end

	private
	def bowl_params
		params.require(:bowl).permit(:id, :left_right, :front_back, :depth, :bottom_grid, :colander, :specsheet_id)
	end

	def load_specsheet
		@specsheet = Specsheet.find(params[:specsheet_id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  user = login(params[:email], params[:password])
	  if user
	  	if session[:return_to_specsheet]
	  		redirect_to session[:return_to_specsheet]
	  		session[:return_to_specsheet] = nil
	  	else
	  		redirect_to user_path(@user), :notice => "Logged in!"
	  	end
	  else
	    flash.now.alert = "Email or password was invalid"
	    render :new
	  end
	end

	def destroy
	  logout
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/specsheets_controller.rb
class SpecsheetsController < ApplicationController
 #before_filter :load_bowls
	def index
		@specsheets = Specsheets.all
	end

	def show
		if !logged_in?
			session[:return_to_specsheet] = request.url
		end
		@specsheet = Specsheet.find(params[:id])
		@bowl = @specsheet.bowls.all
	end

	def new
		@specsheet = Specsheet.new
	end

	def create
		@specsheet = Specsheet.new(specsheet_params)
		#number_of_bowls = params[:bowls].to_i
		if @specsheet.save
			# number_of_bowls.times do 
	 	# 		@bowl = @specsheet.bowls.build
	 	# 		@bowl.save
	 	# 		@bowl.specsheet_id = @specsheet.id
	 	#	end
			redirect_to edit_specsheet_path(@specsheet)
		else
			render :new
		end
	end

	def edit


		@specsheet = Specsheet.find(params[:id])
		@bowls = @specsheet.bowls.all
	end

	def update
		@specsheet = Specsheet.find(params[:id])
		
		if @specsheet.update_attributes(specsheet_params)
			if current_user
				@specsheet.user_id = current_user.id
			end
			if params[:bowls].present? && @specsheet.bowls.count == 0
				number_of_bowls = params[:bowls].to_i
				@all_bowls = []
			 	number_of_bowls.times do 
 		 			@bowl = @specsheet.bowls.build
 		 			@bowl.save
 		 			@all_bowls << @bowl
 		 		end
 		 	# add an else statement before I crash again, boom!!! :-(
 		 	else
 	
 		 	end
 		 	respond_to do |format|
 		 		format.html { redirect_to specsheet_path(@specsheet) }
 		 		format.json { render json: { results: 
	 				@all_bowls.map do |b| 
	 					{
	 					url: specsheet_bowl_path(@specsheet, b), 
	 					id: b.id
	 					}
	 				end
	 			} }
 		 	end
		else
			respond_to do |format|
				format.html { redirect_to specsheet_path(@specsheet) }
				format.json { render json: { url: specsheet_bowl_path(@specsheet, @bowl) } }
			end
		end
	end

	def delete
		@specsheet = Specsheet.find(params[:id])
		@specsheet.destory
		redirect_to specsheets_path
	end

	private
	def specsheet_params
		params.require(:specsheet).permit(:name, :number_of_bowls, :installation, :corner_radius, :drain_location, :drain_size, :divider, :user_id)
	end

	# def load_bowls
	# 	@bowl = @specsheet.bowls.all
	# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
        	auto_login(@user)
        	if session[:return_to_specsheet]
        		redirect_to session[:return_to_specsheet]
        		session[:return_to_specsheet] = nil
        	else
        		redirect_to user_path(@user), :notice => "Signed Up!"
        	end
      	else
        	render :new
      end
	end

	private
	def user_params
	  params.require(:user).permit(:email, :password, :salt)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bowls_helper.rb
module BowlsHelper
end

app/helpers/session_helper.rb
module SessionHelper



end

app/helpers/specsheets_helper.rb
module SpecsheetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bowls/new.html.erb
<h1>Bowls</h2>

<% @specsheet.bowls.each do |bowl| %>

<%= form_for [@specsheet, bowl] do |f| %>
	
	<div class="field">
		<%= f.label :left_right, 'Left to Right' %> <br />
		<%= f.number_field :left_right, in: 8..32 %>
	</div>

	<div class="field">
		<%= f.label :front_back, 'Front to Back' %> <br />
		<%= f.number_field :front_back, in: 8..25 %>
	</div>

	<div class="field">
		<%= f.label :depth, 'Depth' %> <br />
		<%= f.number_field :depth, in: 3..15 %>
	</div>

	<div class="field">
		<%= f.label :bottom_grid, 'Bottom Grid' %> <br />
		<%= f.radio_button :bottom_grid, true %>
		<%= f.label :bottom_grid, 'Include' %> <br />		
		<%= f.radio_button :bottom_grid, false %>
		<%= f.label :bottom_grid, 'Do not include' %> <br />
	</div>


	<div class="field">
		<%= f.label :colander, 'Colander' %> <br />
		<%= f.radio_button :colander, true %>
		<%= f.label :colander, 'Include' %> <br />		
		<%= f.radio_button :colander, false %>
		<%= f.label :colander, 'Do not include' %> <br />
	</div>


	<div class="actions"><%= f.submit %></div>

<% end %>

<% end %>

app/views/bowls/show.html.erb
<% if @specsheet.bowls.any? %>
<div class ="row">
	<% @specsheet.bowls.each do |bowl| %>
	<div class="large-4 columns">
	<fieldset>
		<legend>Bowl</legend>
		<ul class = "no-bullet">
			<li>Left-right: <%= bowl.left_right %></li>
			<li>Front-back: <%= bowl.front_back %></li>
			<li>Depth: <%= bowl.depth %></li>
			<li>Bottom grid: <%= bowl.bottom_grid %></li>
			<li>Colander: <%= bowl.colander %></li>
		</ul>
	</fieldset>
	</div>

	<% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Header and Nav -->  
  <div class="row" style = "margin-bottom:7%">
    <div class="large-4 columns" >
      <h4><%=link_to image_tag("/mekal.png"), new_specsheet_path %> SpecMaker</h4>
    </div>
    <div class="large-8 columns">
      <ul class="inline-list right">
        <% if current_user %>
          <li><%= link_to "My specsheets", user_path(current_user) %></li>
          <li>Signed in as <%= link_to current_user.email, user_path(current_user) %></li>
          <li><%= link_to "Log out", session_path("current"), :method => :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_session_path %></li>
          <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <!-- End Header and Nav -->
  
  
  <div class="row">    
    
    <!-- Main Content Section -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="large-9 push-1 columns">
      
      <%= yield %>
            
    </div>
    
  </div>
<!-- 
  <section>
       <div class="frame">
           <div class="col1 main-content">
              <% if flash[:notice] %>
                <p id="notice"><%= flash[:notice] %></p>
              <% end %>
              <% if flash[:alert] %>
                <p id="alert"><%= flash[:alert] %></p>
              <% end %>
           </div>
       </div>
   </section> -->
  
  
  <!-- Footer -->
  
  <footer class="row" style= "margin-top: 5%">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-12 columns">
          <p>© Copyright helloheathergraham, itsheitor!</p>
        </div>
      </div>
    </div> 
  </footer>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/specsheet_steps/step3.html.erb
<h2>Configuration</h2>
<%= form_for @specsheet, url: wizard_path do |f| %>

<% if @specsheet.errors.any? %>
      <div id="error_explanation">
        <h3><%= pluralize(@specsheet.errors.count, "error") %> prohibited this reservation from being saved:</h3>
        <ul>
        <% @specsheet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

	<div class="field">
		<%= f.label :installation, 'Installation' %> <br />
		<%= f.hidden_field :installation, value: ''%>
		<%= f.radio_button :installation, 'undermount' %>
		<%= f.label :installation, 'Undermount' %> <br />
		<%= f.radio_button :installation, 'overmount' %>
		<%= f.label :installation, 'Overmount' %><br />
	</div>

	<div class="field">
		<%= f.label :corner_radius, 'Corner Radius' %> <br />
		<%= f.hidden_field :corner_radius, value: '' %>
		<%= f.radio_button :corner_radius, '0mm' %> 
		<%= f.label :corner_radius, '0mm' %> <br />
		<%= f.radio_button :corner_radius, '10mm' %> 
		<%= f.label :corner_radius, '10mm' %> <br />
		<%= f.radio_button :corner_radius, '25mm' %> 
		<%= f.label :corner_radius, '25mm' %> <br />
		<%= f.radio_button :corner_radius, '55mm' %>
		<%= f.label :corner_radius, '55mm' %> <br />
	</div>

	<div class="field">
		<%= f.label :drain_location, 'Drain Location' %> <br />
		<%= f.hidden_field :drain_location, value: '' %>
		<%= f.radio_button :drain_location, 'center' %> 
		<%= f.label :drain_location, 'Center' %> <br />
		<%= f.radio_button :drain_location, 'rear' %> 
		<%= f.label :drain_location, 'Rear/Offset' %> <br />
		<%= f.radio_button :drain_location, 'left' %> 
		<%= f.label :drain_location, 'Left' %> <br />
		<%= f.radio_button :drain_location, 'right' %>
		<%= f.label :drain_location, 'Right' %> <br />
	</div>

	<div class="field">
		<%= f.label :drain_size, 'Drain Size' %> <br />
		<%= f.hidden_field :drain_size, value: '' %>
		<%= f.radio_button :drain_size, '3.5"' %>
		<%= f.label :drain_size, '3.5"' %> <br />
		<%= f.radio_button :drain_size, '2.25"' %>
		<%= f.label :drain_size, '2.25"' %><br />
	</div>

	<div class="field">
		<%= f.label :divider, 'Divider' %> <br />
		<%= f.hidden_field :divider, value: '' %>
		<%= f.radio_button :divider, 'normal' %>
		<%= f.label :divider, 'Normal' %> <br />
		<%= f.radio_button :divider, 'lower' %>
		<%= f.label :divider, 'Lower/Normal' %> <br />
		<%= f.radio_button :divider, 'thin' %>
		<%= f.label :divider, 'Lower/Thin' %> <br />
	</div>

	<div class="actions"><%= f.submit %><%= link_to 'Skip this step', next_wizard_path %><%= link_to 'Previous step', previous_wizard_path %></div>

<% end %>

app/views/specsheets/_bowls.html.erb
<% @specsheet.bowls.each do |bowl| %>
	<div class="large-4 columns">
	<fieldset>
		<legend>Bowl</legend>
		<ul class = "no-bullet">
			<li>Left-right: <%= bowl.left_right %></li>
			<li>Front-back: <%= bowl.front_back %></li>
			<li>Depth: <%= bowl.depth %></li>
			<li>Bottom grid: <%= bowl.bottom_grid %></li>
			<li>Colander: <%= bowl.colander %></li>
		</ul>
	</fieldset>
	</div>
<% end %>

app/views/specsheets/_step1.html.erb
<%= form_for @specsheet, html: { class: "select_bowl_amt" } do |f| %>
<div class="field">
	<%= f.hidden_field :id %>
	<%= label :bowls, 'Number of Bowls'%> <br />
	<%= radio_button_tag(:bowls, 1, params[:bowls]) %> 
	<%= label_tag :bowls, 'Single Bowl', :class => 'specsheet' %> <br />
	<%= radio_button_tag(:bowls, 2, params[:bowls]) %>
	<%= label_tag :bowls, 'Double Bowl', :class => 'specsheet' %> <br />
	<%= radio_button_tag(:bowls, 3, params[:bowls]) %> 
	<%= label_tag :bowls, 'Triple Bowl', :class => 'specsheet' %> <br />
</div>

<%= f.submit %>
<% end %>

app/views/specsheets/_step2.html.erb
<% if @specsheet.bowls.any? %>
	<%= form_for ([@specsheet, @bowl])  do |bowl_fields| %>
		<% if @specsheet.errors.any? %>
	      <div id="error_explanation">
	        <h2><%= pluralize(@bowls.errors.count, "error") %> prohibited this reservation from being saved:</h2>

	        <ul>
	        <% @bowls.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	        </ul>
	      </div>
	    <% end %>

		<div class="field">
			<%= bowl_fields.label :left_right, 'Left to Right' %> <br />
			<%= bowl_fields.number_field :left_right, in: 8..32 %>
		</div>

		<div class="field">
			<%= bowl_fields.label :front_back, 'Front to Back' %> <br />
			<%= bowl_fields.number_field :front_back, in: 8..25 %>
		</div>

		<div class="field">
			<%= bowl_fields.label :depth, 'Depth' %> <br />
			<%= bowl_fields.number_field :depth, in: 3..15 %>
		</div>

		<div class="field">
			<%= bowl_fields.label :bottom_grid, 'Bottom Grid' %> <br />
			<%= bowl_fields.radio_button :bottom_grid, true %>
			<%= bowl_fields.label :bottom_grid, 'Include' %> <br />		
			<%= bowl_fields.radio_button :bottom_grid, false %>
			<%= bowl_fields.label :bottom_grid, 'Do not include' %> <br />
		</div>

		<div class="field">
			<%= bowl_fields.label :colander, 'Colander' %> <br />
			<%= bowl_fields.radio_button :colander, true %>
			<%= bowl_fields.label :colander, 'Include' %> <br />		
			<%= bowl_fields.radio_button :colander, false %>
			<%= bowl_fields.label :colander, 'Do not include' %> <br />
		</div>

	<div class="actions"><%= f.submit %></div>

	<% end %>
<% end %>	

app/views/specsheets/_step3.html.erb
<div class="field">
	<%= f.label :installation, 'Installation' %> <br />
	<%= f.hidden_field :installation, value: ''%>
	<%= f.radio_button :installation, 'undermount' %>
	<%= f.label :installation, 'Undermount' %> <br />
	<%= f.radio_button :installation, 'overmount' %>
	<%= f.label :installation, 'Overmount' %><br />
</div>

<div class="field">
	<%= f.label :corner_radius, 'Corner Radius' %> <br />
	<%= f.hidden_field :corner_radius, value: '' %>
	<%= f.radio_button :corner_radius, '0mm' %> 
	<%= f.label :corner_radius, '0mm' %> <br />
	<%= f.radio_button :corner_radius, '10mm' %> 
	<%= f.label :corner_radius, '10mm' %> <br />
	<%= f.radio_button :corner_radius, '25mm' %> 
	<%= f.label :corner_radius, '25mm' %> <br />
	<%= f.radio_button :corner_radius, '55mm' %>
	<%= f.label :corner_radius, '55mm' %> <br />
</div>

<div class="field">
	<%= f.label :drain_location, 'Drain Location' %> <br />
	<%= f.hidden_field :drain_location, value: '' %>
	<%= f.radio_button :drain_location, 'center' %> 
	<%= f.label :drain_location, 'Center' %> <br />
	<%= f.radio_button :drain_location, 'rear' %> 
	<%= f.label :drain_location, 'Rear/Offset' %> <br />
	<%= f.radio_button :drain_location, 'left' %> 
	<%= f.label :drain_location, 'Left' %> <br />
	<%= f.radio_button :drain_location, 'right' %>
	<%= f.label :drain_location, 'Right' %> <br />
</div>

<div class="field">
	<%= f.label :drain_size, 'Drain Size' %> <br />
	<%= f.hidden_field :drain_size, value: '' %>
	<%= f.radio_button :drain_size, '3.5"' %>
	<%= f.label :drain_size, '3.5"' %> <br />
	<%= f.radio_button :drain_size, '2.25"' %>
	<%= f.label :drain_size, '2.25"' %><br />
</div>

<div class="field">
	<%= f.label :divider, 'Divider' %> <br />
	<%= f.hidden_field :divider, value: '' %>
	<%= f.radio_button :divider, 'normal' %>
	<%= f.label :divider, 'Normal' %> <br />
	<%= f.radio_button :divider, 'lower' %>
	<%= f.label :divider, 'Lower/Normal' %> <br />
	<%= f.radio_button :divider, 'thin' %>
	<%= f.label :divider, 'Lower/Thin' %> <br />
</div>

app/views/specsheets/new.html.erb
<div class="small-11 medium-9 large-9 large-centered columns" id ="new">
<h4>Let's build the specsheet for your new sink, mon!</h4>


<div class ="panel">
<%= form_for [@specsheet] do |f| %>
  <% if @specsheet.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@specsheet.errors.count, "error") %> prohibited this reservation from being saved:</h2>

        <ul>
        <% @specsheet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.text_field :name, :placeholder => 'Enter the name of your specsheet...'%>

<%= f.submit :class => "button expand "%>
<% end %>
</div>
</div>

app/views/specsheets/show.html.erb
<!-- <p>Number of Bowls: <%= @specsheet.number_of_bowls %></p> -->

<% @bowlcount = 0 %>

<div class = "row" id = "comments-frame">
	<fieldset>
		<legend><%= "Specsheet: #{@specsheet.name}" %></legend>
			<row>
				<h4>Bowls</h4>
				<div class="large-6 columns">
					<% @specsheet.bowls.each do |bowl| %>
					<h3><%="Bowl" %></h3>
						<%= "Left to right:" %><br />
						<%= "Front to back:" %><br />
						<%= "Depth:" %><br />
						<%= "Bottom grid:" %><br />
						<%= "Colander:" %><br />
				</div>
				<div class="large-6 columns">
					<h3><%="#{@bowlcount + 1}" %></h3>
						<%= "#{bowl.left_right}" %><br />
						<%= "#{bowl.front_back}" %><br />
						<%= "#{bowl.depth}" %><br />
						<%= "#{bowl.bottom_grid}" %><br />
						<%= "#{bowl.colander}" %><br />
					<% end %>
				</div>
				<br>

					<h4>Configuration</h4>
				<div class ="large-6 columns">
					<%= "Installation type:" %><br />
					<%= "Corner radius:" %><br />
					<%= "Drain location:" %><br />
					<%= "Drain size:" %><br />
					<%= "Divider:" %>
				</div>
				<div class ="large-6 columns">
					<%= "#{@specsheet.installation}" %><br />
					<%= "#{@specsheet.corner_radius}" %><br />
					<%= "#{@specsheet.drain_location}" %><br />
					<%= "#{@specsheet.drain_size}" %><br />
					<%= "#{@specsheet.divider}" %>
				</div>

			</row>

	</fieldset>
</div>






<% if current_user %>
<div class="large-12 columns" id ="button">

	<%= form_for @specsheet do |f| %>

	<%= f.hidden_field :id %>	

		<%= f.submit "Save", :class => "button" %>

	<% end %>

</div>
<% else %>
  <p>If you would like to save this specsheet to a personal list <%= link_to "sign up now", new_user_path %>.</p>
 <p>Otherwise, <%= link_to "log in", new_session_path %> to save your specsheet.</p> 
<% end %>

app/views/specsheets/step3.html.erb
<%= form_for (@specsheet) do |f| %>

	<div class="field">
		<%= f.label :installation, 'Installation' %> <br />
		<%= f.radio_button :installation, 'undermount' %>
		<%= f.label :installation, 'Undermount' %> <br />
		<%= f.radio_button :installation, 'overmount' %>
		<%= f.label :installation, 'Overmount' %><br />
	</div>

	<div class="field">
		<%= f.label :corner_radius, 'Corner Radius' %> <br />
		<%= f.radio_button :corner_radius, '0mm' %> 
		<%= f.label :corner_radius, '0mm' %> <br />
		<%= f.radio_button :corner_radius, '10mm' %> 
		<%= f.label :corner_radius, '10mm' %> <br />
		<%= f.radio_button :corner_radius, '25mm' %> 
		<%= f.label :corner_radius, '25mm' %> <br />
		<%= f.radio_button :corner_radius, '55mm' %>
		<%= f.label :corner_radius, '55mm' %> <br />
	</div>

	<div class="field">
		<%= f.label :drain_location, 'Drain Location' %> <br />
		<%= f.radio_button :drain_location, 'center' %> 
		<%= f.label :drain_location, 'Center' %> <br />
		<%= f.radio_button :drain_location, 'rear' %> 
		<%= f.label :drain_location, 'Rear/Offset' %> <br />
		<%= f.radio_button :drain_location, 'left' %> 
		<%= f.label :drain_location, 'Left' %> <br />
		<%= f.radio_button :drain_location, 'right' %>
		<%= f.label :drain_location, 'Right' %> <br />
	</div>

	<div class="field">
		<%= f.label :drain_size, 'Drain Size' %> <br />
		<%= f.radio_button :drain_size, '3.5"' %>
		<%= f.label :drain_size, '3.5"' %> <br />
		<%= f.radio_button :drain_size, '2.25"' %>
		<%= f.label :drain_size, '2.25"' %><br />
	</div>

	<div class="field">
		<%= f.label :divider, 'Divider' %> <br />
		<%= f.radio_button :divider, 'normal' %>
		<%= f.label :divider, 'Normal' %> <br />
		<%= f.radio_button :divider, 'lower' %>
		<%= f.label :divider, 'Lower/Normal' %> <br />
		<%= f.radio_button :divider, 'thin' %>
		<%= f.label :divider, 'Lower/Thin' %> <br />
	</div>

	<div class="actions"><%= f.submit %></div>

<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

List of all users. sub list of specsheets with "date created" "date last edited"?

app/views/users/new.html.erb
<div class="small-11 medium-9 large-9 large-centered columns">
<h4>Sign up if you want to save your specsheet</h4>
<div class = "panel">
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :placeholder => 'Enter your e-mail...' %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder => 'Choose a password' %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder => 'Enter the password again' %>
  </div>
  <%= f.submit :class => "button expand "%>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="row">
</div>

<div class="row">
<div class="large-9 large-centered columns">
<h4>My Specsheets</h4>
<table>
  <thead>
    <tr>
      <th width="200">Name</th>
      <th width="150">Date Created</th>
      <th width="150">Date Last Updated</th>
    </tr>
  </thead>
  <tbody>
<% @user.specsheets.each do |specsheet| %>
    <tr>
      <td><%= link_to specsheet.name, specsheet_path(specsheet)%> </td>
      <td><%= specsheet.created_at %> </td>
      <td><%= specsheet.updated_at %> </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
</div>